#!/bin/bash

## Data Import
## This script imports data to the Restart data warehouse for use by data analytics tools e.g. Metabase
## Only a subset of tables are imported
## This is intended to be run relatively infrequently, e.g. nightly, to refresh the data warehouse
##
## Optionally pass a sql filename as first parameter to load this into the data warehouse rather than fetching from Fixometer

SCRIPT_PATH=`(cd \`dirname $0\`/..; pwd)`

TMPAREA=`mktemp -d`

echo ""
echo "Loading configuation settings..."
source $SCRIPT_PATH/config/fixometer.db.config
source $SCRIPT_PATH/config/repairdir.db.config

while read line; do
  eval TARGET_$line
done < $SCRIPT_PATH/config/warehouse.db.config

echo ""
echo "Pulling Fixometer data..."
TARGET_FILE=$TMPAREA/fixometer.sql
ssh -p $FIXO_PORT $FIXO_SSH_USER@$FIXO_HOST "mysqldump -u $FIXO_DB_USER --single-transaction --compress --password='$FIXO_DB_PASSWORD' --default-character-set=utf8mb4 $FIXO_DB_NAME" > $TARGET_FILE
echo "Done."

echo ""
echo "Pulling Repair Directory data..."
TARGET_FILE_REPAIRDIR=$TMPAREA/repairdirectory.sql
ssh -p $REPAIRDIR_PORT $REPAIRDIR_SSH_USER@$REPAIRDIR_HOST "mysqldump -u $REPAIRDIR_DB_USER --single-transaction --compress --password='$REPAIRDIR_DB_PASSWORD' --default-character-set=utf8mb4 $REPAIRDIR_DB_NAME" > $TARGET_FILE_REPAIRDIR
echo "Done."

# Not using direct MySQL connection as MySQL not currently open to outside connections.
# TBD whether should prefer that over ssh connection.
# mysqldump -u $SOURCE_DB_USER --single-transaction --compress -p$SOURCE_DB_PASSWORD --host=$SOURCE_DB_HOST --port=$SOURCE_DB_PORT $SOURCE_DB_NAME $SOURCE_TABLES > $TARGET_FILE

echo ""
echo "Loading into warehouse..."

echo ""
echo "Restarters.net..."

echo ""
echo "Find/replace on DB info..."
sed -i "s/$FIXO_DB_NAME/$TARGET_DB_NAME/g" $TARGET_FILE
sed -i "s/$FIXO_DB_USER_ORIGINAL/$TARGET_DB_USER_METABASE/g" $TARGET_FILE

echo ""
echo "Load data..."
mysql -u$TARGET_DB_USER_LOADER -p$TARGET_DB_PASSWORD --host=$TARGET_DB_HOST --port=$TARGET_DB_PORT $TARGET_DB_NAME < $TARGET_FILE

echo ""
echo "Repair Directory..."

echo ""
echo "Load data..."
mysql -u$TARGET_DB_USER_LOADER -p$TARGET_DB_PASSWORD --host=$TARGET_DB_HOST --port=$TARGET_DB_PORT warehouse_repairdirectory < $TARGET_FILE_REPAIRDIR

echo "Done."

echo ""
echo "Add time dimension table to aid Metabase queries..."
mysql -u$TARGET_DB_USER_LOADER -p$TARGET_DB_PASSWORD --host=$TARGET_DB_HOST --port=$TARGET_DB_PORT $TARGET_DB_NAME < $SCRIPT_PATH/scripts/createTimeDimension.sql
echo "Done."

echo ""
echo "Fix character encodings (only required until we fix this upstream)..."
mysql -u$TARGET_DB_USER_LOADER -p$TARGET_DB_PASSWORD --host=$TARGET_DB_HOST --port=$TARGET_DB_PORT $TARGET_DB_NAME < $SCRIPT_PATH/scripts/fixCharacterEncodings.sql
echo "Done."

echo ""
echo "Removing temporary working area: $TMPAREA"
rm -rf $TMPAREA

echo ""
echo "Finished."

exit 0
